# Generated by Django 5.1.5 on 2025-03-15 18:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('Tools', 'Tools'), ('Study', 'Study'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=20)),
                ('product_description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='product_images/')),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuySell.items')),
            ],
        ),
    ]
