# Generated by Django 5.1.7 on 2025-03-16 13:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuySell', '0002_alter_cart_table_alter_items_table'),
        ('login', '0002_users_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuySell.items')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
            options={
                'db_table': 'buysell_wishlist',
                'unique_together': {('item', 'usn')},
            },
        ),
    ]
