# Generated by Django 5.1.5 on 2025-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('contact_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
